robot.name = EXAMPLE-ARM

# define first motor subsystem, more subsystems would be robot.motor1, robot.motor2, ...
# robot.motor0.name = "myArm"
# the subsystem ("simple" | "arm" | "elevator" | "flywheel")
myArm.motor.subsystemChild = "arm"
myArm.motor.motorController = "talonFX"
# All motors will have an io setting
myArm.IOSetting.inverted = false
myArm.IOSetting.gearing = 5.0
myArm.IOSetting.drumRadiusMeters = 1.0

myArm.IOSetting.pid.kp = 1.0
myArm.IOSetting.pid.ki = 0.0
myArm.IOSetting.pid.kd = 0.0


# the io settings must are with the motorController defined above
myArm.talonFX.setting.id = 20


# the setting for the arm must start with the name defined above
myArm.setting.minAngleInDegrees = 0.0
myArm.setting.maxAngleInDegrees = 180.0
myArm.setting.startingAngleInDegrees = 90.0

myArm.setting.maxVelocityInDegreesPerSecond = 45.0
myArm.setting.maxAccelerationInDegreesPerSecondSquared = 180.0

# these values are asuming that the angle in in radians
myArm.setting.feedforward.ks = 0.0
myArm.setting.feedforward.kg = 0.0
myArm.setting.feedforward.kv = 0.0

myArm.setting.color.red = 255
myArm.setting.color.blue = 255
myArm.setting.color.green = 0

myArm.setting.DCMotor = KrakenX60
myArm.setting.simulateGravity = true
myArm.setting.armLengthInMeters = 0.5
myArm.setting.armMassInKg = 1

