robot.name = EXAMPLE-CTRE
robot.drive = ctre


#all tuner constants start with ctre
#when an value is an enum value the name mys
ctre.steerGains.kp = 100.0
ctre.steerGains.ki = 0.0
ctre.steerGains.kd = 0.5
ctre.steerGains.ks = 0.1
ctre.steerGains.kv = 2.66
ctre.steerGains.ka = 0.0
#when an value is an enum constant, the value must match the name of the enum constant excatly
ctre.steerGains.staticFeedforwardSign = UseClosedLoopSign

ctre.driveGains.kp = 0.1
ctre.driveGains.ki = 0.0
ctre.driveGains.kd = 0.0
ctre.driveGains.ks = 0.0
ctre.driveGains.kv = 0.124

ctre.steerClosedLoopOutput = Voltage
ctre.driveClosedLoopOutput = Voltage

ctre.steerMotorType = TalonFX_Integrated
ctre.driveMotorType = TalonFX_Integrated
ctre.steerFeedbackType = FusedCANcoder

ctre.slipCurrentInAmps = 120.0
ctre.steerStatorCurrentLimitInAmps = 60.0

ctre.canbus.name = ""
ctre.canbus.hootFilePath = ./logs/example.hoot

ctre.speedAt12VoltsInMetersPerSecond = 5.03
ctre.coupleRatio = 3.5714285714285716
ctre.driveGearRatio = 6.746031746031747
ctre.steerGearRatio = 21.428571428571427

ctre.wheelRadiusInInches = 2.125
ctre.invertLeftSide = false
ctre.invertRightSide = true

ctre.steerInertiaInKilogramSquareMeters = 0.01
ctre.driveInertiaInKilogramSquareMeters = 0.01

ctre.steerFrictionVoltage = 0.2
ctre.driveFrictionVoltage = 0.2

ctre.pigeonId = 50

ctre.frontLeft.driveMotorId = 10
ctre.frontLeft.steerMotorId = 11
ctre.frontLeft.encoderId = 41
ctre.frontLeft.encoderOffsetInRotations = -0.466552734375
ctre.frontLeft.steerInverted = true
ctre.frontLeft.encoderInverted = false
ctre.frontLeft.xPosInInches = 12.0
ctre.frontLeft.yPosInInches = 12.0

ctre.frontRight.driveMotorId = 16
ctre.frontRight.steerMotorId = 17
ctre.frontRight.encoderId = 44
ctre.frontRight.encoderOffsetInRotations = 0.078369140625
ctre.frontRight.steerInverted = true
ctre.frontRight.encoderInverted = false
ctre.frontRight.xPosInInches = 12.0
ctre.frontRight.yPosInInches = -12.0

ctre.backLeft.driveMotorId = 12
ctre.backLeft.steerMotorId = 13
ctre.backLeft.encoderId = 42
ctre.backLeft.encoderOffsetInRotations = -0.1181640625
ctre.backLeft.steerInverted = true
ctre.backLeft.encoderInverted = false
ctre.backLeft.xPosInInches = -12.0
ctre.backLeft.yPosInInches = 12.0

ctre.backRight.driveMotorId = 14
ctre.backRight.steerMotorId = 15
ctre.backRight.encoderId = 43
ctre.backRight.encoderOffsetInRotations = -0.25732421875
ctre.backRight.steerInverted = true
ctre.backRight.encoderInverted = false
ctre.backRight.xPosInInches = -12.0
ctre.backRight.yPosInInches = -12.0
