robot.name = EXAMPLE-ELEVATOR

# All subsystem properties should start with the name of subsystem (for this example "myElevator")
# the subsystem ("simple" | "arm" | "elevator" | "flywheel")
myElevator.motor.subsystemChild = elevator
# the motorController ("talonFX" | "sparkMax" | "sim")
myElevator.motor.motorController = sim
# All motors will have an io setting
myElevator.IOSettings.inverted = false
myElevator.IOSettings.gearing = 50.0
myElevator.IOSettings.drumRadiusMeters = 1.0

myElevator.IOSettings.pid.kp = 0.01
myElevator.IOSettings.pid.ki = 0.0
myElevator.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myElevator.talonFX.setting.id = 20

# the setting for the elevator must start with the name defined above
myElevator.elevatorSettings.minHeightInMeters = 0.0
myElevator.elevatorSettings.maxHeightInMeters = 2.0
myElevator.elevatorSettings.startingHeightInMeters = 0.0
myElevator.elevatorSettings.targetHeightToleranceInMeters = 0.1

myElevator.elevatorSettings.maxVelocityInMetersPerSecond = 1.0
myElevator.elevatorSettings.maxAccelerationInMetersPerSecondSquared = 8.0

# these values are assuming that the height is in meters
myElevator.elevatorSettings.feedforward.ks = 0.0018266
myElevator.elevatorSettings.feedforward.kg = 1.6525
myElevator.elevatorSettings.feedforward.kv = 0.94619

myElevator.elevatorSettings.color.red = 192
myElevator.elevatorSettings.color.blue = 192
myElevator.elevatorSettings.color.green = 192

myElevator.elevatorSettings.DCMotor = KrakenX60
myElevator.elevatorSettings.simulateGravity = true
myElevator.elevatorSettings.carriageMassKg = 5.0

