robot.name = EXAMPLE-FLYWHEEL

# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
# the subsystem ("simple" | "arm" | "elevator" | "flywheel")
myFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
myFlywheel.motor.motorController = sim
# All motors will have an io setting
myFlywheel.IOSettings.inverted = false
myFlywheel.IOSettings.gearing = 1.0
myFlywheel.IOSettings.drumRadiusMeters = 1.0
myFlywheel.IOSettings.pid.kp = 0.0
myFlywheel.IOSettings.pid.ki = 0.0
myFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myFlywheel.talonFX.setting.id = 20


# the setting for the arm must start with the name defined above
myFlywheel.flywheelSettings.maxVelocityInRPMs = 6000.0
myFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
myFlywheel.flywheelSettings.feedforward.ks = 0.0
myFlywheel.flywheelSettings.feedforward.kv = 0.0

myFlywheel.flywheelSettings.color.red = 255
myFlywheel.flywheelSettings.color.blue = 0
myFlywheel.flywheelSettings.color.green = 0

myFlywheel.flywheelSettings.DCMotor = KrakenX60
myFlywheel.flywheelSettings.moiKgMetersSquared = 0.001

