package frc.robot.config.game.rebuilt2026.tunerConstants;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import edu.wpi.first.units.measure.*;
import frc.robot.subsystems.implementations.drive.generated.CommandSwerveDrivetrain;
import java.util.Properties;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {
  // CAN bus that the devices are located on;
  // All swerve devices must share the same CAN bus
  public final CANBus kCANBus;

  // Theoretical free speed (m/s) at 12 V applied output;
  // This needs to be tuned to your individual robot
  public final LinearVelocity kSpeedAt12Volts;

  public final SwerveDrivetrainConstants DrivetrainConstants;

  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontLeft;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontRight;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackLeft;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackRight;

  public TunerConstants(Properties robotProperties) {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput

    final Slot0Configs steerGains =
        new Slot0Configs()
            .withKP(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.kp", "0.0")))
            .withKI(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.ki", "0.0")))
            .withKD(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.kd", "0.0")))
            .withKS(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.ks", "0.0")))
            .withKV(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.kv", "0.0")))
            .withKA(Double.parseDouble(robotProperties.getProperty("ctre.steerGains.ka", "0.0")))
            .withStaticFeedforwardSign(
                StaticFeedforwardSignValue.valueOf(
                    robotProperties.getProperty(
                        "ctre.steerGains.staticFeedforwardSign", "UNKNOWN")));
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    final Slot0Configs driveGains =
        new Slot0Configs()
            .withKP(Double.parseDouble(robotProperties.getProperty("ctre.driveGains.kp", "0.0")))
            .withKI(Double.parseDouble(robotProperties.getProperty("ctre.driveGains.ki", "0.0")))
            .withKD(Double.parseDouble(robotProperties.getProperty("ctre.driveGains.kd", "0.0")))
            .withKS(Double.parseDouble(robotProperties.getProperty("ctre.driveGains.ks", "0.0")))
            .withKV(Double.parseDouble(robotProperties.getProperty("ctre.driveGains.kv", "0.0")));

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    final ClosedLoopOutputType kSteerClosedLoopOutput =
        ClosedLoopOutputType.valueOf(
            robotProperties.getProperty("ctre.steerClosedLoopOutput", "UNKNOWN"));
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    final ClosedLoopOutputType kDriveClosedLoopOutput =
        ClosedLoopOutputType.valueOf(
            robotProperties.getProperty("ctre.driveClosedLoopOutput", "UNKNOWN"));

    // The type of motor used for the drive motor
    final DriveMotorArrangement kDriveMotorType =
        DriveMotorArrangement.valueOf(
            robotProperties.getProperty("ctre.driveMotorType", "TalonFX_Integrated"));
    // The type of motor used for the drive motor
    final SteerMotorArrangement kSteerMotorType =
        SteerMotorArrangement.valueOf(
            robotProperties.getProperty("ctre.steerMotorType", "TalonFX_Integrated"));

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    final SteerFeedbackType kSteerFeedbackType =
        SteerFeedbackType.valueOf(robotProperties.getProperty("ctre.steerFeedbackType", "UNKNOWN"));

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    final Current kSlipCurrent =
        Amps.of(Double.parseDouble(robotProperties.getProperty("ctre.slipCurrentInAmps", "120.0")));

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
    final TalonFXConfiguration steerInitialConfigs =
        new TalonFXConfiguration()
            .withCurrentLimits(
                new CurrentLimitsConfigs()
                    // Swerve azimuth does not require much torque output, so we can set a
                    // relatively
                    // low
                    // stator current limit to help avoid brownouts without impacting performance.
                    .withStatorCurrentLimit(
                        Amps.of(
                            Double.parseDouble(
                                robotProperties.getProperty(
                                    "ctre.steerStatorCurrentLimitInAmps", "60.0"))))
                    .withStatorCurrentLimitEnable(true));
    final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    kCANBus =
        new CANBus(
            robotProperties.getProperty("ctre.canbus.name", ""),
            robotProperties.getProperty("ctre.canbus.hootFilePath", "./logs/example.hoot"));

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    kSpeedAt12Volts =
        MetersPerSecond.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.speedAt12VoltsInMetersPerSecond", "5.03")));

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    final double kCoupleRatio =
        Double.parseDouble(robotProperties.getProperty("ctre.coupleRatio", "3.5714285714285716"));

    final double kDriveGearRatio =
        Double.parseDouble(robotProperties.getProperty("ctre.driveGearRatio", "6.746031746031747"));
    final double kSteerGearRatio =
        Double.parseDouble(
            robotProperties.getProperty("ctre.steerGearRatio", "21.428571428571427"));
    final Distance kWheelRadius =
        Inches.of(
            Double.parseDouble(robotProperties.getProperty("ctre.wheelRadiusInInches", "1.125")));

    final boolean kInvertLeftSide =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.invertLeftSide", "false"));
    final boolean kInvertRightSide =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.invertRightSide", "false"));

    final int kPigeonId = Integer.parseInt(robotProperties.getProperty("ctre.pigeonId", "0"));

    // These are only used for simulation
    final MomentOfInertia kSteerInertia =
        KilogramSquareMeters.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.steerInertiaInKilogramSquareMeters", "0.01")));
    final MomentOfInertia kDriveInertia =
        KilogramSquareMeters.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.driveInertiaInKilogramSquareMeters", "0.01")));
    // Simulated voltage necessary to overcome friction
    final Voltage kSteerFrictionVoltage =
        Volts.of(
            Double.parseDouble(robotProperties.getProperty("ctre.steerFrictionVoltage", "0.2")));
    final Voltage kDriveFrictionVoltage =
        Volts.of(
            Double.parseDouble(robotProperties.getProperty("ctre.driveFrictionVoltage", "0.2")));

    DrivetrainConstants =
        new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    final SwerveModuleConstantsFactory<
            TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
        ConstantCreator =
            new SwerveModuleConstantsFactory<
                    TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                .withDriveMotorGearRatio(kDriveGearRatio)
                .withSteerMotorGearRatio(kSteerGearRatio)
                .withCouplingGearRatio(kCoupleRatio)
                .withWheelRadius(kWheelRadius)
                .withSteerMotorGains(steerGains)
                .withDriveMotorGains(driveGains)
                .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
                .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
                .withSlipCurrent(kSlipCurrent)
                .withSpeedAt12Volts(kSpeedAt12Volts)
                .withDriveMotorType(kDriveMotorType)
                .withSteerMotorType(kSteerMotorType)
                .withFeedbackSource(kSteerFeedbackType)
                .withDriveMotorInitialConfigs(driveInitialConfigs)
                .withSteerMotorInitialConfigs(steerInitialConfigs)
                .withEncoderInitialConfigs(encoderInitialConfigs)
                .withSteerInertia(kSteerInertia)
                .withDriveInertia(kDriveInertia)
                .withSteerFrictionVoltage(kSteerFrictionVoltage)
                .withDriveFrictionVoltage(kDriveFrictionVoltage);

    // Front Left
    final int kFrontLeftDriveMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontLeft.driveMotorId", "0"));
    final int kFrontLeftSteerMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontLeft.steerMotorId", "0"));
    final int kFrontLeftEncoderId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontLeft.encoderId", "0"));
    final Angle kFrontLeftEncoderOffset =
        Rotations.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.frontLeft.encoderOffsetInRotations", "0.0")));
    final boolean kFrontLeftSteerMotorInverted =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.frontLeft.steerInverted", "false"));
    final boolean kFrontLeftEncoderInverted =
        Boolean.parseBoolean(
            robotProperties.getProperty("ctre.frontLeft.encoderInverted", "false"));
    ;

    final Distance kFrontLeftXPos =
        Inches.of(
            Double.parseDouble(robotProperties.getProperty("ctre.frontLeft.xPosInInches", "12.0")));
    final Distance kFrontLeftYPos =
        Inches.of(
            Double.parseDouble(robotProperties.getProperty("ctre.frontLeft.yPosInInches", "12.0")));

    // Front Right
    final int kFrontRightDriveMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontRight.driveMotorId", "0"));
    final int kFrontRightSteerMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontRight.steerMotorId", "0"));
    final int kFrontRightEncoderId =
        Integer.parseInt(robotProperties.getProperty("ctre.frontRight.encoderId", "0"));
    final Angle kFrontRightEncoderOffset =
        Rotations.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.frontRight.encoderOffsetInRotations", "0.0")));
    final boolean kFrontRightSteerMotorInverted =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.frontRight.steerInverted", "false"));
    final boolean kFrontRightEncoderInverted =
        Boolean.parseBoolean(
            robotProperties.getProperty("ctre.frontRight.encoderInverted", "false"));

    final Distance kFrontRightXPos =
        Inches.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.frontRight.xPosInInches", "12.0")));
    final Distance kFrontRightYPos =
        Inches.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.frontRight.yPosInInches", "-12.0")));

    // Back Left
    final int kBackLeftDriveMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.backLeft.driveMotorId", "0"));
    final int kBackLeftSteerMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.backLeft.steerMotorId", "0"));
    final int kBackLeftEncoderId =
        Integer.parseInt(robotProperties.getProperty("ctre.backLeft.encoderId", "0"));
    final Angle kBackLeftEncoderOffset =
        Rotations.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.backLeft.encoderOffsetInRotations", "0.0")));
    final boolean kBackLeftSteerMotorInverted =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.backLeft.steerInverted", "false"));
    final boolean kBackLeftEncoderInverted =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.backLeft.encoderInverted", "false"));

    final Distance kBackLeftXPos =
        Inches.of(
            Double.parseDouble(robotProperties.getProperty("ctre.backLeft.xPosInInches", "-12.0")));
    final Distance kBackLeftYPos =
        Inches.of(
            Double.parseDouble(robotProperties.getProperty("ctre.backLeft.yPosInInches", "12.0")));

    // Back Right
    final int kBackRightDriveMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.backRight.driveMotorId", "0"));
    final int kBackRightSteerMotorId =
        Integer.parseInt(robotProperties.getProperty("ctre.backRight.steerMotorId", "0"));
    final int kBackRightEncoderId =
        Integer.parseInt(robotProperties.getProperty("ctre.backRight.encoderId", "0"));
    final Angle kBackRightEncoderOffset =
        Rotations.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.backRight.encoderOffsetInRotations", "0.0")));
    final boolean kBackRightSteerMotorInverted =
        Boolean.parseBoolean(robotProperties.getProperty("ctre.backRight.steerInverted", "false"));
    ;
    final boolean kBackRightEncoderInverted =
        Boolean.parseBoolean(
            robotProperties.getProperty("ctre.backRight.encoderInverted", "false"));
    ;

    final Distance kBackRightXPos =
        Inches.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.backRight.xPosInInches", "-12.0")));
    final Distance kBackRightYPos =
        Inches.of(
            Double.parseDouble(
                robotProperties.getProperty("ctre.backRight.yPosInInches", "-12.0")));

    FrontLeft =
        ConstantCreator.createModuleConstants(
            kFrontLeftSteerMotorId,
            kFrontLeftDriveMotorId,
            kFrontLeftEncoderId,
            kFrontLeftEncoderOffset,
            kFrontLeftXPos,
            kFrontLeftYPos,
            kInvertLeftSide,
            kFrontLeftSteerMotorInverted,
            kFrontLeftEncoderInverted);
    FrontRight =
        ConstantCreator.createModuleConstants(
            kFrontRightSteerMotorId,
            kFrontRightDriveMotorId,
            kFrontRightEncoderId,
            kFrontRightEncoderOffset,
            kFrontRightXPos,
            kFrontRightYPos,
            kInvertRightSide,
            kFrontRightSteerMotorInverted,
            kFrontRightEncoderInverted);
    BackLeft =
        ConstantCreator.createModuleConstants(
            kBackLeftSteerMotorId,
            kBackLeftDriveMotorId,
            kBackLeftEncoderId,
            kBackLeftEncoderOffset,
            kBackLeftXPos,
            kBackLeftYPos,
            kInvertLeftSide,
            kBackLeftSteerMotorInverted,
            kBackLeftEncoderInverted);
    BackRight =
        ConstantCreator.createModuleConstants(
            kBackRightSteerMotorId,
            kBackRightDriveMotorId,
            kBackRightEncoderId,
            kBackRightEncoderOffset,
            kBackRightXPos,
            kBackRightYPos,
            kInvertRightSide,
            kBackRightSteerMotorInverted,
            kBackRightEncoderInverted);
  }

  /**
   * Creates a CommandSwerveDrivetrain instance. This should only be called once in your robot
   * program,.
   */
  public CommandSwerveDrivetrain createDrivetrain() {
    return new CommandSwerveDrivetrain(
        DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight);
  }
}
