package frc.robot.config.game.rebuilt2026.tunerConstants;

import static edu.wpi.first.units.Units.*;

import java.util.Properties;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;
import frc.robot.subsystems.implementations.drive.generated.CommandSwerveDrivetrain;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {
    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public final CANBus kCANBus;

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    public final LinearVelocity kSpeedAt12Volts;

    public final SwerveDrivetrainConstants DrivetrainConstants;


    public  final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontLeft;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      FrontRight;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackLeft;
  public final SwerveModuleConstants<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
      BackRight;

    public TunerConstants(Properties simulationProperties) {
        // Both sets of gains need to be tuned to your individual robot.

        // The steer motor uses any SwerveModule.SteerRequestType control request with the
        // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput

        
        final Slot0Configs steerGains =
            new Slot0Configs()
                .withKP(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.kp", "0.0")))
                .withKI(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.ki", "0.0")))
                .withKD(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.kd", "0.0")))
                .withKS(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.ks", "0.0")))
                .withKV(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.kv", "0.0")))
                .withKA(Double.parseDouble(simulationProperties.getProperty("ctre.steerGains.ka", "0.0")))
                .withStaticFeedforwardSign(StaticFeedforwardSignValue.valueOf(simulationProperties.getProperty("ctre.steerGains.staticFeedforwardSign", "UNKNOWN")));
        // When using closed-loop control, the drive motor uses the control
        // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
        final Slot0Configs driveGains =
            new Slot0Configs()
                .withKP(Double.parseDouble(simulationProperties.getProperty("ctre.driveGains.kp", "0.0")))
                .withKI(Double.parseDouble(simulationProperties.getProperty("ctre.driveGains.ki", "0.0")))
                .withKD(Double.parseDouble(simulationProperties.getProperty("ctre.driveGains.kd", "0.0")))
                .withKS(Double.parseDouble(simulationProperties.getProperty("ctre.driveGains.ks", "0.0")))
                .withKV(Double.parseDouble(simulationProperties.getProperty("ctre.driveGains.kv", "0.0")));
        
        // The closed-loop output type to use for the steer motors;
        // This affects the PID/FF gains for the steer motors
        final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.valueOf(simulationProperties.getProperty("ctre.steerClosedLoopOutput", "UNKNOWN"));
        // The closed-loop output type to use for the drive motors;
        // This affects the PID/FF gains for the drive motors
        final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.valueOf(simulationProperties.getProperty("ctre.driveClosedLoopOutput", "UNKNOWN"));
        
        // The type of motor used for the drive motor
        final DriveMotorArrangement kDriveMotorType =
        DriveMotorArrangement.valueOf(simulationProperties.getProperty("ctre.driveMotorType", "TalonFX_Integrated"));
        // The type of motor used for the drive motor
        final SteerMotorArrangement kSteerMotorType =
        SteerMotorArrangement.valueOf(simulationProperties.getProperty("ctre.steerMotorType", "TalonFX_Integrated"));
        
        // The remote sensor feedback type to use for the steer motors;
        // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
        final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.valueOf(simulationProperties.getProperty("ctre.steerFeedbackType", "UNKNOWN"));
        
        // The stator current at which the wheels start to slip;
        // This needs to be tuned to your individual robot
        final Current kSlipCurrent = Amps.of(Double.parseDouble(simulationProperties.getProperty("ctre.slipCurrentInAmps", "120.0")));
        
        // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
        // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
        final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
        final TalonFXConfiguration steerInitialConfigs =
            new TalonFXConfiguration()
                .withCurrentLimits(
                    new CurrentLimitsConfigs()
                        // Swerve azimuth does not require much torque output, so we can set a relatively
                        // low
                        // stator current limit to help avoid brownouts without impacting performance.
                        .withStatorCurrentLimit(Amps.of(Double.parseDouble(simulationProperties.getProperty("ctre.steerStatorCurrentLimitInAmps", "60.0"))))
                        .withStatorCurrentLimitEnable(true));
        final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
        // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
        final Pigeon2Configuration pigeonConfigs = null;
        
        // CAN bus that the devices are located on;
        // All swerve devices must share the same CAN bus
        kCANBus = new CANBus(simulationProperties.getProperty("ctre.canbus.name", ""), simulationProperties.getProperty("ctre.canbus.hootFilePath", "./logs/example.hoot"));
        
        // Theoretical free speed (m/s) at 12 V applied output;
        // This needs to be tuned to your individual robot
        kSpeedAt12Volts = MetersPerSecond.of(Double.parseDouble(simulationProperties.getProperty("ctre.speedAt12VoltsInMetersPerSecond", "5.03")));
        
        // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
        // This may need to be tuned to your individual robot
        final double kCoupleRatio = Double.parseDouble(simulationProperties.getProperty("ctre.coupleRatio", "3.5714285714285716"));
    
        final double kDriveGearRatio = Double.parseDouble(simulationProperties.getProperty("ctre.driveGearRatio", "6.746031746031747"));
        final double kSteerGearRatio = Double.parseDouble(simulationProperties.getProperty("ctre.steerGearRatio", "21.428571428571427"));
        final Distance kWheelRadius = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.wheelRadiusInInches", "1.125")));
    
        final boolean kInvertLeftSide = Boolean.parseBoolean(simulationProperties.getProperty("ctre.invertLeftSide", "false"));
        final boolean kInvertRightSide = Boolean.parseBoolean(simulationProperties.getProperty("ctre.invertRightSide", "false"));
    
        final int kPigeonId = Integer.parseInt(simulationProperties.getProperty("ctre.pigeonId", "0"));
        
        // These are only used for simulation
        final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(Double.parseDouble(simulationProperties.getProperty("ctre.steerInertiaInKilogramSquareMeters", "0.01")));
        final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(Double.parseDouble(simulationProperties.getProperty("ctre.driveInertiaInKilogramSquareMeters", "0.01")));
        // Simulated voltage necessary to overcome friction
        final Voltage kSteerFrictionVoltage = Volts.of(Double.parseDouble(simulationProperties.getProperty("ctre.steerFrictionVoltage", "0.2")));
        final Voltage kDriveFrictionVoltage = Volts.of(Double.parseDouble(simulationProperties.getProperty("ctre.driveFrictionVoltage", "0.2")));
        
        DrivetrainConstants =
            new SwerveDrivetrainConstants()
                .withCANBusName(kCANBus.getName())
                .withPigeon2Id(kPigeonId)
                .withPigeon2Configs(pigeonConfigs);
        
        final SwerveModuleConstantsFactory<
            TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
            ConstantCreator =
                new SwerveModuleConstantsFactory<
                        TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
                    .withDriveMotorGearRatio(kDriveGearRatio)
                    .withSteerMotorGearRatio(kSteerGearRatio)
                    .withCouplingGearRatio(kCoupleRatio)
                    .withWheelRadius(kWheelRadius)
                    .withSteerMotorGains(steerGains)
                    .withDriveMotorGains(driveGains)
                    .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
                    .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
                    .withSlipCurrent(kSlipCurrent)
                    .withSpeedAt12Volts(kSpeedAt12Volts)
                    .withDriveMotorType(kDriveMotorType)
                    .withSteerMotorType(kSteerMotorType)
                    .withFeedbackSource(kSteerFeedbackType)
                    .withDriveMotorInitialConfigs(driveInitialConfigs)
                    .withSteerMotorInitialConfigs(steerInitialConfigs)
                    .withEncoderInitialConfigs(encoderInitialConfigs)
                    .withSteerInertia(kSteerInertia)
                    .withDriveInertia(kDriveInertia)
                    .withSteerFrictionVoltage(kSteerFrictionVoltage)
                    .withDriveFrictionVoltage(kDriveFrictionVoltage);
        
        // Front Left
        final int kFrontLeftDriveMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.frontLeft.driveMotorId", "0"));
        final int kFrontLeftSteerMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.frontLeft.steerMotorId", "0"));
        final int kFrontLeftEncoderId = Integer.parseInt(simulationProperties.getProperty("ctre.frontLeft.encoderId", "0"));
        final Angle kFrontLeftEncoderOffset = Rotations.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontLeft.encoderOffsetInRotations", "0.0")));
        final boolean kFrontLeftSteerMotorInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.frontLeft.steerInverted", "false"));
        final boolean kFrontLeftEncoderInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.frontLeft.encoderInverted", "false"));;
    
        final Distance kFrontLeftXPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontLeft.xPosInInches", "12.0")));
        final Distance kFrontLeftYPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontLeft.yPosInInches", "12.0")));
        
        // Front Right
        final int kFrontRightDriveMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.frontRight.driveMotorId", "0"));
        final int kFrontRightSteerMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.frontRight.steerMotorId", "0"));
        final int kFrontRightEncoderId = Integer.parseInt(simulationProperties.getProperty("ctre.frontRight.encoderId", "0"));
        final Angle kFrontRightEncoderOffset = Rotations.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontRight.encoderOffsetInRotations", "0.0")));
        final boolean kFrontRightSteerMotorInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.frontRight.steerInverted", "false"));
        final boolean kFrontRightEncoderInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.frontRight.encoderInverted", "false"));
    
        final Distance kFrontRightXPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontRight.xPosInInches", "12.0")));
        final Distance kFrontRightYPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.frontRight.yPosInInches", "-12.0")));
        
        // Back Left
        final int kBackLeftDriveMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.backLeft.driveMotorId", "0"));
        final int kBackLeftSteerMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.backLeft.steerMotorId", "0"));
        final int kBackLeftEncoderId = Integer.parseInt(simulationProperties.getProperty("ctre.backLeft.encoderId", "0"));
        final Angle kBackLeftEncoderOffset = Rotations.of(Double.parseDouble(simulationProperties.getProperty("ctre.backLeft.encoderOffsetInRotations", "0.0")));
        final boolean kBackLeftSteerMotorInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.backLeft.steerInverted", "false"));
        final boolean kBackLeftEncoderInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.backLeft.encoderInverted", "false"));
        
        final Distance kBackLeftXPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.backLeft.xPosInInches", "-12.0")));
        final Distance kBackLeftYPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.backLeft.yPosInInches", "12.0")));
        
        // Back Right
        final int kBackRightDriveMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.backRight.driveMotorId", "0"));
        final int kBackRightSteerMotorId = Integer.parseInt(simulationProperties.getProperty("ctre.backRight.steerMotorId", "0"));
        final int kBackRightEncoderId = Integer.parseInt(simulationProperties.getProperty("ctre.backRight.encoderId", "0"));
        final Angle kBackRightEncoderOffset = Rotations.of(Double.parseDouble(simulationProperties.getProperty("ctre.backRight.encoderOffsetInRotations", "0.0")));
        final boolean kBackRightSteerMotorInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.backRight.steerInverted", "false"));;
        final boolean kBackRightEncoderInverted = Boolean.parseBoolean(simulationProperties.getProperty("ctre.backRight.encoderInverted", "false"));;
    
        final Distance kBackRightXPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.backRight.xPosInInches", "-12.0")));
        final Distance kBackRightYPos = Inches.of(Double.parseDouble(simulationProperties.getProperty("ctre.backRight.yPosInInches", "-12.0")));
        
        FrontLeft =
            ConstantCreator.createModuleConstants(
                kFrontLeftSteerMotorId,
                kFrontLeftDriveMotorId,
                kFrontLeftEncoderId,
                kFrontLeftEncoderOffset,
                kFrontLeftXPos,
                kFrontLeftYPos,
                kInvertLeftSide,
                kFrontLeftSteerMotorInverted,
                kFrontLeftEncoderInverted);
        FrontRight =
            ConstantCreator.createModuleConstants(
                kFrontRightSteerMotorId,
                kFrontRightDriveMotorId,
                kFrontRightEncoderId,
                kFrontRightEncoderOffset,
                kFrontRightXPos,
                kFrontRightYPos,
                kInvertRightSide,
                kFrontRightSteerMotorInverted,
                kFrontRightEncoderInverted);
        BackLeft =
            ConstantCreator.createModuleConstants(
                kBackLeftSteerMotorId,
                kBackLeftDriveMotorId,
                kBackLeftEncoderId,
                kBackLeftEncoderOffset,
                kBackLeftXPos,
                kBackLeftYPos,
                kInvertLeftSide,
                kBackLeftSteerMotorInverted,
                kBackLeftEncoderInverted);
        BackRight =
            ConstantCreator.createModuleConstants(
                kBackRightSteerMotorId,
                kBackRightDriveMotorId,
                kBackRightEncoderId,
                kBackRightEncoderOffset,
                kBackRightXPos,
                kBackRightYPos,
                kInvertRightSide,
                kBackRightSteerMotorInverted,
                kBackRightEncoderInverted);
        
    }
//   // Both sets of gains need to be tuned to your individual robot.

//   // The steer motor uses any SwerveModule.SteerRequestType control request with the
//   // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
//   private static final Slot0Configs steerGains =
//       new Slot0Configs()
//           .withKP(100)
//           .withKI(0)
//           .withKD(0.5)
//           .withKS(0.1)
//           .withKV(2.66)
//           .withKA(0)
//           .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
//   // When using closed-loop control, the drive motor uses the control
//   // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
//   private static final Slot0Configs driveGains =
//       new Slot0Configs().withKP(0.1).withKI(0).withKD(0).withKS(0).withKV(0.124);

//   // The closed-loop output type to use for the steer motors;
//   // This affects the PID/FF gains for the steer motors
//   private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
//   // The closed-loop output type to use for the drive motors;
//   // This affects the PID/FF gains for the drive motors
//   private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

//   // The type of motor used for the drive motor
//   private static final DriveMotorArrangement kDriveMotorType =
//       DriveMotorArrangement.TalonFX_Integrated;
//   // The type of motor used for the drive motor
//   private static final SteerMotorArrangement kSteerMotorType =
//       SteerMotorArrangement.TalonFX_Integrated;

//   // The remote sensor feedback type to use for the steer motors;
//   // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
//   private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

//   // The stator current at which the wheels start to slip;
//   // This needs to be tuned to your individual robot
//   private static final Current kSlipCurrent = Amps.of(120.0);

//   // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
//   // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
//   private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
//   private static final TalonFXConfiguration steerInitialConfigs =
//       new TalonFXConfiguration()
//           .withCurrentLimits(
//               new CurrentLimitsConfigs()
//                   // Swerve azimuth does not require much torque output, so we can set a relatively
//                   // low
//                   // stator current limit to help avoid brownouts without impacting performance.
//                   .withStatorCurrentLimit(Amps.of(60))
//                   .withStatorCurrentLimitEnable(true));
//   private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
//   // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
//   private static final Pigeon2Configuration pigeonConfigs = null;

//   // CAN bus that the devices are located on;
//   // All swerve devices must share the same CAN bus
//   public static final CANBus kCANBus = new CANBus("", "./logs/example.hoot");

//   // Theoretical free speed (m/s) at 12 V applied output;
//   // This needs to be tuned to your individual robot
//   public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(5.03);

//   // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
//   // This may need to be tuned to your individual robot
//   private static final double kCoupleRatio = 3.5714285714285716;

//   private static final double kDriveGearRatio = 6.746031746031747;
//   private static final double kSteerGearRatio = 21.428571428571427;
//   private static final Distance kWheelRadius = Inches.of(2.125);

//   private static final boolean kInvertLeftSide = false;
//   private static final boolean kInvertRightSide = true;

//   private static final int kPigeonId = 50;

//   // These are only used for simulation
//   private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
//   private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
//   // Simulated voltage necessary to overcome friction
//   private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
//   private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

//   public static final SwerveDrivetrainConstants DrivetrainConstants =
//       new SwerveDrivetrainConstants()
//           .withCANBusName(kCANBus.getName())
//           .withPigeon2Id(kPigeonId)
//           .withPigeon2Configs(pigeonConfigs);

//   private static final SwerveModuleConstantsFactory<
//           TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
//       ConstantCreator =
//           new SwerveModuleConstantsFactory<
//                   TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
//               .withDriveMotorGearRatio(kDriveGearRatio)
//               .withSteerMotorGearRatio(kSteerGearRatio)
//               .withCouplingGearRatio(kCoupleRatio)
//               .withWheelRadius(kWheelRadius)
//               .withSteerMotorGains(steerGains)
//               .withDriveMotorGains(driveGains)
//               .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
//               .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
//               .withSlipCurrent(kSlipCurrent)
//               .withSpeedAt12Volts(kSpeedAt12Volts)
//               .withDriveMotorType(kDriveMotorType)
//               .withSteerMotorType(kSteerMotorType)
//               .withFeedbackSource(kSteerFeedbackType)
//               .withDriveMotorInitialConfigs(driveInitialConfigs)
//               .withSteerMotorInitialConfigs(steerInitialConfigs)
//               .withEncoderInitialConfigs(encoderInitialConfigs)
//               .withSteerInertia(kSteerInertia)
//               .withDriveInertia(kDriveInertia)
//               .withSteerFrictionVoltage(kSteerFrictionVoltage)
//               .withDriveFrictionVoltage(kDriveFrictionVoltage);

//   // Front Left
//   private static final int kFrontLeftDriveMotorId = 10;
//   private static final int kFrontLeftSteerMotorId = 11;
//   private static final int kFrontLeftEncoderId = 41;
//   private static final Angle kFrontLeftEncoderOffset = Rotations.of(-0.466552734375);
//   private static final boolean kFrontLeftSteerMotorInverted = true;
//   private static final boolean kFrontLeftEncoderInverted = false;

//   private static final Distance kFrontLeftXPos = Inches.of(12);
//   private static final Distance kFrontLeftYPos = Inches.of(12);

//   // Front Right
//   private static final int kFrontRightDriveMotorId = 16;
//   private static final int kFrontRightSteerMotorId = 17;
//   private static final int kFrontRightEncoderId = 44;
//   private static final Angle kFrontRightEncoderOffset = Rotations.of(0.078369140625);
//   private static final boolean kFrontRightSteerMotorInverted = true;
//   private static final boolean kFrontRightEncoderInverted = false;

//   private static final Distance kFrontRightXPos = Inches.of(12);
//   private static final Distance kFrontRightYPos = Inches.of(-12);

//   // Back Left
//   private static final int kBackLeftDriveMotorId = 12;
//   private static final int kBackLeftSteerMotorId = 13;
//   private static final int kBackLeftEncoderId = 42;
//   private static final Angle kBackLeftEncoderOffset = Rotations.of(-0.1181640625);
//   private static final boolean kBackLeftSteerMotorInverted = true;
//   private static final boolean kBackLeftEncoderInverted = false;

//   private static final Distance kBackLeftXPos = Inches.of(-12);
//   private static final Distance kBackLeftYPos = Inches.of(12);

//   // Back Right
//   private static final int kBackRightDriveMotorId = 14;
//   private static final int kBackRightSteerMotorId = 15;
//   private static final int kBackRightEncoderId = 43;
//   private static final Angle kBackRightEncoderOffset = Rotations.of(-0.25732421875);
//   private static final boolean kBackRightSteerMotorInverted = true;
//   private static final boolean kBackRightEncoderInverted = false;

//   private static final Distance kBackRightXPos = Inches.of(-12);
//   private static final Distance kBackRightYPos = Inches.of(-12);

//   public static final SwerveModuleConstants<
//           TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
//       FrontLeft =
//           ConstantCreator.createModuleConstants(
//               kFrontLeftSteerMotorId,
//               kFrontLeftDriveMotorId,
//               kFrontLeftEncoderId,
//               kFrontLeftEncoderOffset,
//               kFrontLeftXPos,
//               kFrontLeftYPos,
//               kInvertLeftSide,
//               kFrontLeftSteerMotorInverted,
//               kFrontLeftEncoderInverted);
//   public static final SwerveModuleConstants<
//           TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
//       FrontRight =
//           ConstantCreator.createModuleConstants(
//               kFrontRightSteerMotorId,
//               kFrontRightDriveMotorId,
//               kFrontRightEncoderId,
//               kFrontRightEncoderOffset,
//               kFrontRightXPos,
//               kFrontRightYPos,
//               kInvertRightSide,
//               kFrontRightSteerMotorInverted,
//               kFrontRightEncoderInverted);
//   public static final SwerveModuleConstants<
//           TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
//       BackLeft =
//           ConstantCreator.createModuleConstants(
//               kBackLeftSteerMotorId,
//               kBackLeftDriveMotorId,
//               kBackLeftEncoderId,
//               kBackLeftEncoderOffset,
//               kBackLeftXPos,
//               kBackLeftYPos,
//               kInvertLeftSide,
//               kBackLeftSteerMotorInverted,
//               kBackLeftEncoderInverted);
//   public static final SwerveModuleConstants<
//           TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>
//       BackRight =
//           ConstantCreator.createModuleConstants(
//               kBackRightSteerMotorId,
//               kBackRightDriveMotorId,
//               kBackRightEncoderId,
//               kBackRightEncoderOffset,
//               kBackRightXPos,
//               kBackRightYPos,
//               kInvertRightSide,
//               kBackRightSteerMotorInverted,
//               kBackRightEncoderInverted);

  /**
   * Creates a CommandSwerveDrivetrain instance. This should only be called once in your robot
   * program,.
   */
  public CommandSwerveDrivetrain createDrivetrain() {
    return new CommandSwerveDrivetrain(
        DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight);
  }

  /** Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types. */
  public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
      super(TalonFX::new, TalonFX::new, CANcoder::new, drivetrainConstants, modules);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set
     *     to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules) {
      super(
          TalonFX::new,
          TalonFX::new,
          CANcoder::new,
          drivetrainConstants,
          odometryUpdateFrequency,
          modules);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set
     *     to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
     *     [x, y, theta]ᵀ, with units in meters and radians
     * @param visionStandardDeviation The standard deviation for vision calculation in the form [x,
     *     y, theta]ᵀ, with units in meters and radians
     * @param modules Constants for each specific module
     */
    public TunerSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules) {
      super(
          TalonFX::new,
          TalonFX::new,
          CANcoder::new,
          drivetrainConstants,
          odometryUpdateFrequency,
          odometryStandardDeviation,
          visionStandardDeviation,
          modules);
    }
  }
}
